In [1]:
import numpy as np

In [2]:
# 1D array from Python list
a = np.array([1, 2, 3, 4, 5])

# zeros and ones
b = np.zeros((2, 3))
c = np.ones((3, 3))

# ranges
d = np.arange(0, 10, 2)      # 0, 2, 4, 6, 8
e = np.linspace(0, 1, 5)     # 5 точек от 0 до 1

print("a:", a)
print("b:\n", b)
print("c:\n", c)
print("d:", d)
print("e:", e)


a: [1 2 3 4 5]
b:
 [[0. 0. 0.]
 [0. 0. 0.]]
c:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
d: [0 2 4 6 8]
e: [0.   0.25 0.5  0.75 1.  ]


In [3]:
print("a.shape:", a.shape)
print("a.dtype:", a.dtype)
print("a.ndim:", a.ndim)

print("b.shape:", b.shape)
print("b.dtype:", b.dtype)


a.shape: (5,)
a.dtype: int64
a.ndim: 1
b.shape: (2, 3)
b.dtype: float64


In [4]:
arr = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]

print("arr:", arr)
print("first element:", arr[0])
print("last element:", arr[-1])
print("slice 2:7:", arr[2:7])
print("every second element:", arr[::2])


arr: [0 1 2 3 4 5 6 7 8 9]
first element: 0
last element: 9
slice 2:7: [2 3 4 5 6]
every second element: [0 2 4 6 8]


In [5]:
m = np.arange(1, 10).reshape(3, 3)
print("matrix m:\n", m)

print("element m[0, 1]:", m[0, 1])   # первая строка, второй столбец
print("first row:", m[0, :])
print("second column:", m[:, 1])
print("submatrix 0:2, 1:3:\n", m[0:2, 1:3])


matrix m:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
element m[0, 1]: 2
first row: [1 2 3]
second column: [2 5 8]
submatrix 0:2, 1:3:
 [[2 3]
 [5 6]]


In [6]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

print("x + y:", x + y)
print("x * y:", x * y)
print("x squared:", x ** 2)

print("mean of x:", x.mean())
print("sum of x:", x.sum())
print("max of x:", x.max())


x + y: [11 22 33 44]
x * y: [ 10  40  90 160]
x squared: [ 1  4  9 16]
mean of x: 2.5
sum of x: 10
max of x: 4
